"""Sample listings seeded on first startup."""
from decimal import Decimal

SAMPLE_LISTINGS: list[dict] = [
    {
        "title": "Sea Pearl Beach Suite",
        "description": "Beachfront suite with panoramic Bay of Bengal views, king bed, and private balcony.",
        "location": "Cox's Bazar",
        "address": "Sea Pearl Beach Resort, Kolatoli, Cox's Bazar",
        "price_per_night_bdt": 6500,
        "max_guests": 2,
        "amenities": ["wifi", "ac", "breakfast", "pool", "beach_access"],
        "photos": [],
        "rating": Decimal("4.8"),
    },
    {
        "title": "Sayeman Heritage Studio",
        "description": "Comfortable studio in a heritage hotel a short walk from Laboni Beach.",
        "location": "Cox's Bazar",
        "address": "Sayeman Beach Resort, Hotel Motel Zone, Cox's Bazar",
        "price_per_night_bdt": 4200,
        "max_guests": 2,
        "amenities": ["wifi", "ac", "breakfast"],
        "photos": [],
        "rating": Decimal("4.3"),
    },
    {
        "title": "Long Beach Apartment",
        "description": "Spacious self-catering apartment 200 m from the beach, great for families.",
        "location": "Cox's Bazar",
        "address": "Long Beach Hotel Area, Cox's Bazar",
        "price_per_night_bdt": 3800,
        "max_guests": 4,
        "amenities": ["wifi", "ac", "kitchen"],
        "photos": [],
        "rating": Decimal("4.1"),
    },
    {
        "title": "Mermaid Eco Resort Cottage",
        "description": "Secluded eco-cottage 10 km north of Cox's Bazar town; ideal for couples.",
        "location": "Cox's Bazar",
        "address": "Mermaid Beach Resort, Patenga Road, Cox's Bazar",
        "price_per_night_bdt": 5500,
        "max_guests": 3,
        "amenities": ["wifi", "ac", "breakfast", "pool"],
        "photos": [],
        "rating": Decimal("4.6"),
    },
    {
        "title": "Laboni Beach Guest House",
        "description": "Budget-friendly room with sea view, minutes from Laboni Beach.",
        "location": "Cox's Bazar",
        "address": "Laboni Point, Cox's Bazar",
        "price_per_night_bdt": 2800,
        "max_guests": 2,
        "amenities": ["wifi", "ac"],
        "photos": [],
        "rating": Decimal("3.9"),
    },
    {
        "title": "The Westin Dhaka Deluxe Room",
        "description": "5-star deluxe room in Gulshan, Dhaka — ideal for business travellers.",
        "location": "Dhaka",
        "address": "The Westin Dhaka, 1 Minto Road, Ramna, Dhaka",
        "price_per_night_bdt": 8500,
        "max_guests": 2,
        "amenities": ["wifi", "ac", "breakfast", "gym", "pool"],
        "photos": [],
        "rating": Decimal("4.7"),
    },
    {
        "title": "Rose View Hotel Sylhet Standard",
        "description": "Modern standard room with tea-garden views in central Sylhet.",
        "location": "Sylhet",
        "address": "Rose View Hotel, Airport Road, Sylhet",
        "price_per_night_bdt": 3200,
        "max_guests": 2,
        "amenities": ["wifi", "ac", "breakfast"],
        "photos": [],
        "rating": Decimal("4.2"),
    },
    {
        "title": "Sundarban Eco Lodge",
        "description": "Riverside eco-lodge at the edge of the Sundarban mangrove forest.",
        "location": "Khulna",
        "address": "Mongla, Bagerhat, Khulna Division",
        "price_per_night_bdt": 4800,
        "max_guests": 4,
        "amenities": ["wifi", "breakfast", "boat_tour"],
        "photos": [],
        "rating": Decimal("4.5"),
    },
]
